#!/usr/bin/env python3
"""Build and verify the site's single, release-versioned CSS bundle."""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
BUNDLE = ROOT / "assets/css/site.bundle.css"
CRITICAL = ROOT / "assets/css/site.critical.css"
SOURCES = (
    ROOT / "assets/css/sitekit/reset.css",
    ROOT / "assets/css/sitekit/tokens.css",
    ROOT / "assets/css/sitekit/themes.css",
    ROOT / "assets/css/sitekit/base.css",
    ROOT / "assets/css/sitekit/components.css",
    ROOT / "assets/css/sitekit/utilities.css",
    ROOT / "assets/css/site.css",
)
URL_PATTERN = re.compile(r"url\((?P<quote>['\"]?)(?P<url>[^)'\"]+)(?P=quote)\)")
CRITICAL_COMPONENTS = (".sk-breadcrumbs", ".sk-button", ".sk-header")


def rewrite_urls(css: str, source: Path, *, absolute: bool = False) -> str:
    """Resolve local URLs from each source file relative to the bundle."""

    def replace(match: re.Match[str]) -> str:
        url = match.group("url").strip()
        if url.startswith(("data:", "http:", "https:", "#")):
            return match.group(0)
        path, separator, fragment = url.partition("#")
        path, query_separator, _query = path.partition("?")
        target = (source.parent / path).resolve()
        if absolute:
            relative = "/" + target.relative_to(ROOT).as_posix()
        else:
            relative = Path(os.path.relpath(target, BUNDLE.parent)).as_posix()
        suffix = f"?v={VERSION}"
        if separator:
            suffix += f"#{fragment}"
        quote = match.group("quote")
        return f"url({quote}{relative}{suffix}{quote})"

    return URL_PATTERN.sub(replace, css)


def render_bundle() -> str:
    sections = [
        f"/* RobertDeVore.com v{VERSION}; generated by scripts/bundle_css.py. */"
    ]
    for source in SOURCES:
        if not source.is_file():
            raise FileNotFoundError(f"missing CSS source: {source.relative_to(ROOT)}")
        css = source.read_text(encoding="utf-8").strip()
        sections.append(
            f"/* source: {source.relative_to(ROOT).as_posix()} */\n"
            f"{rewrite_urls(css, source)}"
        )
    return "\n".join(sections) + "\n"


def component_blocks(css: str) -> list[str]:
    """Return balanced top-level @layer blocks from SiteKit components."""

    blocks: list[str] = []
    cursor = 0
    while True:
        start = css.find("@layer", cursor)
        if start < 0:
            return blocks
        opening = css.find("{", start)
        if opening < 0:
            raise ValueError("unbalanced SiteKit component layer")
        depth = 0
        for index in range(opening, len(css)):
            if css[index] == "{":
                depth += 1
            elif css[index] == "}":
                depth -= 1
                if depth == 0:
                    blocks.append(css[start : index + 1])
                    cursor = index + 1
                    break
        else:
            raise ValueError("unbalanced SiteKit component layer")


def render_critical() -> str:
    """Render stable above-the-fold CSS while the complete bundle loads."""

    critical_sources = SOURCES[:4]
    sections = [
        f"/* RobertDeVore.com v{VERSION} critical CSS; generated by scripts/bundle_css.py. */"
    ]
    for source in critical_sources:
        css = source.read_text(encoding="utf-8").strip()
        sections.append(rewrite_urls(css, source, absolute=True))
    components_source = SOURCES[4]
    components = components_source.read_text(encoding="utf-8")
    selected = [
        block
        for block in component_blocks(components)
        if any(
            re.match(
                rf"@layer\s+components\s*\{{\s*{re.escape(marker)}(?:\s|\{{|,|:)",
                block,
            )
            for marker in CRITICAL_COMPONENTS
        )
    ]
    if len(selected) != len(CRITICAL_COMPONENTS):
        raise ValueError("expected one SiteKit block for each critical component")
    sections.extend(
        rewrite_urls(block, components_source, absolute=True) for block in selected
    )
    for source in SOURCES[5:]:
        css = source.read_text(encoding="utf-8").strip()
        sections.append(rewrite_urls(css, source, absolute=True))
    return "\n".join(sections) + "\n"


def write_atomically(destination: Path, payload: str) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(payload)
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when the committed bundle is stale"
    )
    args = parser.parse_args()
    expected = {BUNDLE: render_bundle(), CRITICAL: render_critical()}
    if args.check:
        stale = [
            path.relative_to(ROOT)
            for path, payload in expected.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != payload
        ]
        if stale:
            print("CSS bundle is stale; run: python3 scripts/bundle_css.py", file=sys.stderr)
            print("Stale: " + ", ".join(str(path) for path in stale), file=sys.stderr)
            return 1
        print(f"CSS bundle checks passed for RobertDeVore.com v{VERSION}.")
        return 0
    for path, payload in expected.items():
        write_atomically(path, payload)
        print(f"Wrote {path.relative_to(ROOT)} for RobertDeVore.com v{VERSION}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
