#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SSG="${SSG_ROOT:-/Users/robertdevore/2026/Kujolang/kujo-repos/ssg}"
SK="${SITEKIT_ROOT:-/Users/robertdevore/2026/Kujolang/kujo-repos/site-kit}"
cp "$SSG/build.kujo" "$ROOT/build.kujo"
cp "$SK/css/reset.css" "$ROOT/assets/css/sitekit/reset.css"
cp "$SK/css/generated/tokens.css" "$ROOT/assets/css/sitekit/tokens.css"
cp "$SK/css/generated/themes.css" "$ROOT/assets/css/sitekit/themes.css"
cp "$SK/css/base.css" "$ROOT/assets/css/sitekit/base.css"
cp "$SK/css/generated/components.css" "$ROOT/assets/css/sitekit/components.css"
cp "$SK/css/utilities.css" "$ROOT/assets/css/sitekit/utilities.css"
cp "$SK/fonts/DepartureMono-Regular.woff2" "$ROOT/assets/fonts/"
cp "$SK/fonts/DepartureMono-Regular.woff" "$ROOT/assets/fonts/"
cp "$SK/fonts/DepartureMono-LICENSE.txt" "$ROOT/assets/fonts/"
echo "Synced Kujo SSG and SiteKit distribution assets."
